### DISCUSSION TITLE
Having difficulties with styling

### DISCUSSION THREAD

**Discussion by JamesSingleton** [wojtekmaj/react-pdf#1631] [Q&A]
I wanted to just kind of get up and running with this library so I borrowed some of the styles from [next-app](https://github.com/wojtekmaj/react-pdf/blob/main/sample/next-app/app/Sample.css) example.

Here is the code rendering it

```tsx
<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
  {data.pdfs.map((pdf) => (
    <div
      key={pdf._key}
      className="p-2 border rounded flex flex-col items-center"
    >
      <h3 className="text-lg font-bold text-center">{pdf.title}</h3>
      <div className="Example__container">
        <div className="Example__container__document">
          <PDFComponent url={pdf.file} />
        </div>
      </div>
      <Button className="mt-2">
        <DownloadIcon className="mr-2 h-4 w-4" /> Download
      </Button>
    </div>
  ))}
</div>
```

And this is the custom component

```tsx
'use client'

import { useState } from 'react'
import { pdfjs, Document, Page } from 'react-pdf'
import 'react-pdf/dist/esm/Page/AnnotationLayer.css'
import 'react-pdf/dist/esm/Page/TextLayer.css'

import type { PDFDocumentProxy } from 'pdfjs-dist'

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url,
).toString()

const options = {
  cMapUrl: '/cmaps/',
  standardFontDataUrl: '/standard_fonts/',
}

type PDFFile = string | File | null

export default function PDFComponent({ url }: { url: string }) {
  const [file, setFile] = useState<PDFFile>()
  const [numPages, setNumPages] = useState<number>()

  function onFileChange(event: React.ChangeEvent<HTMLInputElement>): void {
    const { files } = event.target

    if (files && files[0]) {
      setFile(files[0] || null)
    }
  }

  function onDocumentLoadSuccess({
    numPages: nextNumPages,
  }: PDFDocumentProxy): void {
    setNumPages(nextNumPages)
  }

  return (
    <Document
      file={url}
      onLoadSuccess={onDocumentLoadSuccess}
      options={options}
    >
      {Array.from(new Array(numPages), (el, index) => (
        <Page key={`page_${index + 1}`} pageNumber={index + 1} />
      ))}
    </Document>
  )
}
```
However, it looks like there's an _issue_ with the PDF rendering outside of the div as you can see in the screenshot below.

![Screenshot 2023-10-06 at 8 43 00 PM](https://github.com/wojtekmaj/react-pdf/assets/21000200/417e4f4c-7795-4810-b2ce-cb46b212ac2c)

This is causing an issue because you can't click on the `download` button and you can select a bunch of empty space because there's content from `react-pdf` there.

Any help would be greatly appreciated! I am sure I am just styling it incorrectly.

**Comment by JamesSingleton** [comment]
So I ended up just using `<Thumbnail />` and then updating the CSS to

```css
.Example__container__document .react-pdf__Document {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.Example__container__document .react-pdf__Thumbnail__page {
  max-width: calc(100% - 2em);
  box-shadow: 0 0 8px rgba(0, 0, 0, 0.5);
  margin: 1em;
}

.Example__container__document .react-pdf__Thumbnail__page canvas {
  max-width: 100%;
  height: auto !important;
}

.Example__container__document .react-pdf__message {
  padding: 20px;
  color: white;
}
```

And it seems to have done the trick
