### ISSUE TITLE
Highlight font formatting and style

### ISSUE THREAD

**Issue by raf-microsoft** [wojtekmaj/react-pdf#1932]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When I run search in the pdf.js the highlight works nicely, the font is the same as the pdf and the styling looks correct.  

![image](https://github.com/user-attachments/assets/f3eb82e4-dc97-44cc-9c7e-fd3f553b8da5)

when I do the same based on `Wiki` the fonts are inconsistent, and the highlight is a bit of 

![image](https://github.com/user-attachments/assets/fa7e6efe-0575-48e3-8dfa-14651fe562b2)

### Steps to reproduce

Run the example form the `Wiki` https://github.com/wojtekmaj/react-pdf/wiki/Recipes

### Expected behaviour

The highlight fonts should follow the document fonts.

### Actual behaviour

The size & style of the font is inconsistent.

### Environment

All latest.

**Comment by raf-microsoft** [comment]
The same happens when the text is selected: 
![image](https://github.com/user-attachments/assets/3f377747-ce23-4279-b8d2-241b041453ce)

**Comment by mchen10** [comment]
+1 on this. Am seeing similar issues on some documents

<img width="749" alt="Image" src="https://github.com/user-attachments/assets/f5ab257c-5e07-4717-960e-787b57793c38" />

**Comment by chandrasekhar-IMP** [comment]
Any update on this @wojtekmaj ?

**Comment by bytemain** [comment]
You can use this css to override the style:

```css

/* 让选中态的文字背景色覆盖而不显示文字本身 */
.textLayer ::selection {
  background: rgba(0, 0, 255, 0.3) !important;
  color: transparent !important;
}

.textLayer ::-moz-selection {
  background: rgba(0, 0, 255, 0.3) !important;
  color: transparent !important;
}
```
