### ISSUE TITLE
What component you used on your site for page navigation? 

### ISSUE THREAD

**Issue by sundriver** [wojtekmaj/react-pdf#607]
**What are you trying to achieve? Please describe.**

I am trying to make a online pdf reader with page navigation exactly to what you have on your website, with page navigation buttons overlaid on top of the pdf file.

Is there any chance you can share the react source code for the page ? or some advise to recreate it.

**Comment by wojtekmaj** [comment]
There's really nothing fancy going on there :)

```jsx

      <div className="page-controls">
        <button
          disabled={pageNumber <= 1}
          onClick={() => setPageNumber(pageNumber - 1)}
          type="button"
          aria-label="Previous page"
        >
          ‹
        </button>
        <span>
          {pageNumber}
          {' '}
          of
          {' '}
          {numPages}
        </span>
        <button
          disabled={pageNumber >= numPages}
          onClick={() => setPageNumber(pageNumber + 1)}
          type="button"
          aria-label="Next page"
        >
          ›
        </button>
      </div>
```

```less
.react-pdf__Document {
  position: relative;

  &:hover {
    .page-controls {
      opacity: 1;
    }
  }
}

.page-controls {
  position: absolute;
  bottom: 5%;
  left: 50%;
  background: white;
  opacity: 0;
  transform: translateX(-50%);
  transition: opacity ease-in-out 0.2s;
  .shadow();
  .rounded-corners();

  span {
    font: inherit;
    font-size: .8em;
    padding: 0 .5em;
  }

  button {
    width: 44px;
    height: 44px;
    background: white;
    border: 0;
    font: inherit;
    font-size: .8em;
    .rounded-corners();

    &:enabled {
      &:hover {
        cursor: pointer;
      }

      &:hover, &:focus {
        background-color: #e6e6e6;
      }
    }

    &:first-child {
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
    }

    &:last-child {
      border-top-left-radius: 0;
      border-bottom-left-radius: 0;
    }
  }
}

```

**Comment by HarryWangATX** [comment]
Hi @wojtekmaj, thanks for making this! My CSS file is having trouble with your style code above, is there any reason why?

**Comment by wojtekmaj** [comment]
Likely because of LESS mixins. I have recently reviewed the code and migrated it to pure CSS. I can update the comment if you need it :)

**Comment by HarryWangATX** [comment]
So I did a little bit of tinkering and ended up with this CSS.

```css
.react-pdf__Page__canvas {
  margin: 20px auto;
  width: 80% !important;
  height: 100% !important;
}

.react-pdf__Document {
  position: relative;
  margin: auto;
}
.react-pdf__Document:hover .page-controls {
  opacity: 1;
}
.page-controls {
  position: absolute;
  bottom: 5%;
  left: 50%;
  color: black;
  background: white;
  border-radius: 10px;
  opacity: 0;
  transform: translateX(-50%);
  transition: opacity ease-in-out 0.2s;
}
.page-controls span {
  font: inherit;
  font-size: .8em;
  padding: 0 .5em;
}
.page-controls button {
  width: 44px;
  height: 44px;
  background: white;
  border: 0;
  border-radius: 10px;
  font: inherit;
  font-size: .8em;
}
.page-controls button:enabled:hover {
  cursor: pointer;
}
.page-controls button:enabled:hover, .page-controls button:enabled:focus {
  background-color: #e6e6e6;
}
.page-controls button:first-child {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
.page-controls button:last-child {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
```

However, after I click the button, it doesn't unshadow. I'd appreciate it if you can point out where to add so it de-shadows the button. Thanks!
