### ISSUE TITLE
Second copy of pdfjs

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-pdf#927]
Thanks, that worked. I'm not sure why I have a second copy of pdfjs. Nowhere in my package.json I have it as a dependency or I have other packages that could install it as a dependency. I tried deleting my node_modules and reinstalling but it appeared again. I use npm so it's not a big issue.

_Originally posted by @albireox in https://github.com/wojtekmaj/react-pdf/issues/912#issuecomment-1017007365_

**Comment by wojtekmaj** [comment]
Share your package-lock.json or yarn.lock and we'll figure it out. If it's related to React-PDF we'll create another thread in order not to spam people.

_Originally posted by @wojtekmaj in https://github.com/wojtekmaj/react-pdf/issues/912#issuecomment-1017122266_

**Comment by wojtekmaj** [comment]
Here they are.

[Archive.zip](https://github.com/wojtekmaj/react-pdf/files/7902506/Archive.zip)

_Originally posted by @albireox in https://github.com/wojtekmaj/react-pdf/issues/912#issuecomment-1017130145_

**Comment by wojtekmaj** [comment]
Ah yes, that makes it clear.

```
"@types/react-pdf@npm:^5.0.9":
  version: 5.0.9
  resolution: "@types/react-pdf@npm:5.0.9"
  dependencies:
    "@types/react": "*"
    pdfjs-dist: ^2.10.377
  checksum: 5247dd76dc20beb504f13756d576d4036dab19416de648553f6405b44d4cf8467be3d50063f98cc07eed39b37d07bc834756a3f275b8bc7f635226fd59ae17c7
  languageName: node
  linkType: hard
```

```
"pdfjs-dist@npm:2.10.377":
  version: 2.10.377
  resolution: "pdfjs-dist@npm:2.10.377"
  peerDependencies:
    worker-loader: ^3.0.7
  checksum: 5a4c14777676e15aeca9a627cc1f368821071ae040154983edf21f1040cb89acd9b0168b43b64ac10d66f86094dcb48b33513b9810b6d422446c599fb172d5a4
  languageName: node
  linkType: hard

"pdfjs-dist@npm:^2.10.377":
  version: 2.12.313
  resolution: "pdfjs-dist@npm:2.12.313"
  peerDependencies:
    worker-loader: ^3.0.8
  peerDependenciesMeta:
    worker-loader:
      optional: true
  checksum: 0571ff3653d75e7eaf86c840c6fe83a92456c20b6f40c2de666df2e3c30de1e05a4920f18799a3d59005c73dcea1a6f45728845a20fdae9b08a3a774d13aee1b
  languageName: node
  linkType: hard
```

so, it's actually a bug in `@types/react-pdf`, it may download a newer version of pdfjs-dist than used by React-PDF.
