### ISSUE TITLE
Text layer elements are out of alignment horizontally

### ISSUE THREAD

**Issue by niktnikt** [wojtekmaj/react-pdf#976]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hey!
The text layer is out of alignment horizontally (as shown in the screenshot). It seems like the spacing between the individual words of the text layer is too large. I tried testing the same PDF on the PDF.js demo and it works completely fine.

![Selection_033](https://user-images.githubusercontent.com/37475603/161396976-c57beafc-52c7-4dea-a56f-78f6319b6582.png)

### Steps to reproduce

Happens for most PDFs in my case.

### Expected behavior

The text layer should match the content

### Actual behavior

The text layer is out of alignment horizontalyl.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
May be fixed by #944

**Comment by reteps** [comment]
This unfortunately did not solve my issue. Had to still use custom CSS to hide the text layer, as the fonts weren't aligned.

```css
/* Hide text layer of PDF */
.react-pdf__Page__textContent  {
  color: transparent;
  opacity: 0.5;
}
.react-pdf__Page__textContent ::selection {
  background: #0000ff;
}
```
